---
- name: Install Dokku
  sudo: yes
  hosts: dokku
  vars:
    public_key: '~/.ssh/id_rsa.pub'
    swap_file_path: /swapfile
    swap_file_size_kb: 1048576
    dokku_plugins:
      - https://github.com/ohardy/dokku-mariadb
      - https://github.com/ohardy/dokku-psql

  roles:
    - swap
    - dokku

  post_tasks:

    - name: Add Public Key into Dokku user
      authorized_key: user=dokku key="{{ lookup('file', public_key) }}"

    - name: Start MariaDB
      shell: dokku mariadb:start
